CREATE TABLE IF NOT EXISTS meta.column_governance (table_schema text NOT NULL,table_name text NOT NULL,column_name text NOT NULL,sensitivity_level text NOT NULL CHECK (sensitivity_level IN ('Restricted','Confidential','Sensitive','Internal')),pii_flag boolean NOT NULL DEFAULT false,phi_flag boolean NOT NULL DEFAULT false,financial_flag boolean NOT NULL DEFAULT false,business_owner text NOT NULL,masking_strategy text NOT NULL,powerbi_exposure text NOT NULL,business_definition text,validation_requirement text,PRIMARY KEY(table_schema,table_name,column_name));
CREATE TABLE IF NOT EXISTS meta.quality_rule (rule_id bigserial PRIMARY KEY,rule_name text UNIQUE NOT NULL,table_name text NOT NULL,column_name text,dimension text NOT NULL CHECK (dimension IN ('Completeness','Validity','Uniqueness','Integrity','Consistency','Business Rule')),severity text NOT NULL CHECK(severity IN ('Critical','High','Medium','Low')),rule_sql text NOT NULL,active boolean NOT NULL DEFAULT true);
-- Metadata drives generated classification: direct/contact, health and finance column patterns are separately controlled.
INSERT INTO meta.column_governance(table_schema,table_name,column_name,sensitivity_level,pii_flag,phi_flag,financial_flag,business_owner,masking_strategy,powerbi_exposure,business_definition,validation_requirement)
SELECT 'landing',c.table_name,c.column_name,
 CASE WHEN c.column_name ~ '(customer_name|phone_number|nominee_name|referral_name|^name$)' THEN 'Restricted' WHEN c.column_name ~ '(bmi|blood_pressure|smoking|alcohol|risk|test|preexisting|medication|medical)' THEN 'Restricted' WHEN c.column_name ~ '(income|premium|assured|amount|expenses|ticket)' THEN 'Confidential' WHEN c.column_name ~ '(^.*_id$|utm|engagement|follow_up|conversion|drop_off|lead_status|lead_stage)' THEN 'Confidential' WHEN c.column_name ~ '(gender|marital|occupation|language|age|joining_date)' THEN 'Sensitive' ELSE 'Internal' END,
 c.column_name ~ '(customer_name|phone_number|nominee_name|referral_name|^name$|_id$|gender|marital|occupation|language|age|joining_date|risk|test|preexisting|medication)',
 c.column_name ~ '(bmi|blood_pressure|smoking|alcohol|risk|test|preexisting|medication|medical)',c.column_name ~ '(income|premium|assured|amount|expenses|ticket)',
 'Enterprise Data Governance',CASE WHEN c.column_name ~ '(customer_name|phone_number|nominee_name|referral_name|^name$)' THEN 'Suppress or pseudonymize' WHEN c.column_name ~ '(bmi|blood_pressure|smoking|alcohol|risk|test|preexisting|medication|medical)' THEN 'Exclude; expose approved risk band only' ELSE 'RBAC and aggregation where required' END,
 CASE WHEN c.column_name ~ '(customer_name|phone_number|nominee_name|referral_name|^name$|bmi|blood_pressure|smoking|alcohol|risk|test|preexisting|medication|medical)' THEN 'Not permitted' ELSE 'Approved mart only' END,
 initcap(replace(c.column_name,'_',' ')) || ' captured in supplied ' || c.table_name || '.', 'Profile and validate before use'
FROM information_schema.columns c WHERE c.table_schema='landing' AND c.column_name <> 'loaded_at'
ON CONFLICT (table_schema,table_name,column_name) DO NOTHING;
